module.exports = [
    {
        name:"C++",
        title:"Learn C++ Basics",
        date:"January 2015",
        image:"./images/c++.png",
        link:"https://www.youtube.com/watch?v=Iuo9PpGE04Y&list=PLLYz8uHU480j37APNXBdPz7YzAi4XlQUF",
        description:"This is the complete course on the data structure and algorithm through C++.",
    },
    {
        name:"Web Development",
        title:"Learn Web D",
        date:"January 2017",
        image:"./images/wevd.jpeg",
        link:"https://www.youtube.com/watch?v=6mbwJ2xhgzM&list=PLu0W_9lII9agiCUZYRsvtGTXdxkzPyItg",
        description:"The course is accordance with the most recent web developerment trends.",
    },
    {
        name:"Python",
        title:"Learn pyhton",
        date:"August 2010",
        image:"./images/python.png",
        link:"https://www.youtube.com/watch?v=RAwntanK4wQ&list=PLwgFb6VsUj_lQTpQKDtLXKXElQychT_2j",
        description:"This is the comlplete course on pyhton .The course is designed for the beginner to expert level in python . ",
    },
    {
        name:"Android",
        title:"Learn Android Development",
        date:"April 2015",
        image:"./images/Android.jpg",
        link:"https://www.youtube.com/watch?v=InigFUSiPl8&list=PLu0W_9lII9aiL0kysYlfSOUgY5rNlOhUd",
        description:"Android development is one of the most demanding skill in software companies.",
    },
    {
        name:"ML",
        title:"Learn Machine Learning",
        date:"September 2017",
        image:"./images/ml.jfif",
        link:"https://www.youtube.com/watch?v=GwIo3gDZCVQ",
        description:"Machine learning is the science of getting computers to act without being explicitly programmed.",
    },
    {
        name:"AI",
        title:"Learn Artificial Intelligence",
        date:"October 2013",
        image:"./images/ai.jpg",
        link:"https://www.youtube.com/watch?v=UkZzM-jxLv4",
        description:"Explore the fascinating and fast moving field of artificial intelligence .",
    },
    {
        name:"DSA",
        title:"Data Structure & Algorithms",
        date:"April 2018",
        image:"./images/dsa.png",
        link:"https://www.youtube.com/watch?v=8hly31xKli0",
        description:"The course is explicitly designed for advanced data struvture and algorithm",
    },
    {
        name:"CP",
        title:"Learn Competative Programming",
        date:"March 2015",
        image:"./images/cp.png",
        link:"https://www.youtube.com/watch?v=6ZBY9yGNWbI&list=PLzjZaW71kMwTGbP1suqY16w1VSb9ZNuvE",
        description:"Competitive programming is a sport.The course is desined for aceing the competitive-programming.",
    },
    {
        name:"Java",
        title:"Learn Java",
        date:"January 2019",
        image:"./images/java.webp",
        link:"https://www.youtube.com/watch?v=VHbSopMyc4M&list=PLBlnK6fEyqRjKA_NuK9mHmlk0dZzuP1P5",
        description:"This Full Stack Java Development course from beginner to expert level.",
    },
    {
        name:"Robotics",
        title:"Learn Robotics",
        date:"January 2014",
        image:"./images/robot.jpg",
        link:"https://www.youtube.com/watch?v=MBl-3Yb30FA",
        description:"You will be exposed to real world examples of how robots have been applied in disaster situations.",
    } 
    
]